---

- hosts: all
  become: true
  tasks:

         - name: update cache (Ubuntu)
           tags: always
           apt:
                   update_cache: yes
           changed_when: false
           when: ansible_distribution == "Ubuntu"
           


