- name: install samba package
  tags: apache,apache2
  copy:
          src: default_site.html
          dest: /var/www/html/index.html
          owner: root
          group: root
          mode: 0644
